server:
  port: 18080

spring:
  application:
    name: week7-board-jpa
  datasource:
    url: jdbc:mariadb://localhost:3306/week5_board
    username: root
    password: "Inter0304!@"
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # 운영 안전 : 스키마 자동 변경 방지
    properties:
      hibernate:
        format_sql: true
        highlight_sql: ture
    open-in-view: false   # OSIV 끄기 (실무표준)

  logging:
    level:
      p6spy: INFO





